version: '3'
services:

  discovery-service:
    image: mgramin/discovery-service
    ports:
      - "8761:8761"
    networks:
      - mynetwork
    depends_on:
      - message-service
      - account-service
      - web-client
    links:
      - message-service
      - account-service
      - web-client

  web-client:
    image: mgramin/web-client
    ports:
      - "9000:9000"
    networks:
      - mynetwork
    environment:
      - DISCOVERY_SERVER=http://discovery-service:8761/eureka/

  message-service:
    image: mgramin/message-service
    ports:
      - "8080:8080"
    entrypoint: dockerize -wait tcp://cassandra_db:9042 -timeout 30s
    command: java -Djava.security.egd=file:/dev/./urandom -Dloader.path='.' -jar ./message-service.jar
    networks:
      - mynetwork
    depends_on:
      - cassandra_db
    links:
      - cassandra_db
    environment:
      - DB_HOST=cassandra_db
      - DB_PORT=9042
      - DISCOVERY_SERVER=http://discovery-service:8761/eureka/

  account-service:
    image: mgramin/account-service
    ports:
      - "8090:8090"
    entrypoint: dockerize -wait tcp://mongo_db:27017 -timeout 30s
    command: java -Djava.security.egd=file:/dev/./urandom -Dloader.path='.' -jar ./account-service.jar
    networks:
      - mynetwork
    depends_on:
      - mongo_db
    links:
      - mongo_db
    environment:
      - DB_HOST=mongo_db
      - DB_PORT=27017
      - DISCOVERY_SERVER=http://discovery-service:8761/eureka/

  cassandra_db:
    image: cassandra:latest
    ports:
      - "9042:9042"
    networks:
      mynetwork:
        aliases:
          - cassandra_server
    hostname: cassandra_server

  mongo_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      mynetwork:
        aliases:
          - mongo_server
    hostname: mongo_server

networks:
  mynetwork:
    driver: bridge